### ISSUE TITLE
npm:@tailwindcss/postcss7-compat 单纯就是兼容 postcss7 的另一个版本，不算降低，因为功能上没有任何区别

### ISSUE THREAD

**Issue by lcysgsg** [sonofmagic/uni-app-vue3-tailwind-vscode-template#1]
>  [To help bridge the gap until everyone has updated, we also publish a PostCSS 7 compatibility build as @tailwindcss/postcss7-compat on npm.
    ...
    The compatibility build is identical to the main build in every way, so you aren’t missing out on any features or anything like that.](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build)

**Comment by sonofmagic** [comment]
是的 @tailwindcss/postcss7-compat 是一个单独包，多谢矫正。
